import brower from './brower';
export default [
  ...brower,
  {
    type: 'root',
    name: '流程',
    canDraggable: false,
    canAfterAdd: false,
    canBeforeAdd: false,
    disabled: false,
    canSelect: false,
  },
  {
    type: 'startNode',
    title: '开始',
    canDraggable: false,
    canAfterAdd: true,
    canBeforeAdd: false,
    disabled: true,
    canSelect: false,
  },
  {
    type: 'endNode',
    title: '结束',
    canDraggable: false,
    canAfterAdd: false,
    canBeforeAdd: true,
    disabled: true,
    canSelect: false,
  },
  {
    type: 'brower_close1',
    title: '关闭网页',
    canDraggable: true,
    canAfterAdd: true,
    canBeforeAdd: true,
    disabled: false,
    canSelect: true,
    description: '在浏览器中关闭网页',
    initProps: [
      {
        name: 'url',
        title: '网页地址',
        component: 'Input',
        defaultValue: 'www.baidu.com',
      },
    ],
  },
  {
    type: 'brower_open1',
    title: '关闭网页1',
    canDraggable: true,
    canAfterAdd: true,
    canBeforeAdd: true,
    disabled: false,
    canSelect: true,
    description: '在浏览器中关闭网页',
    initProps: [
      {
        name: 'url',
        title: '网页地址',
        component: 'Input',
        defaultValue: 'www.baidu.com',
      },
    ],
  },
  {
    type: 'brower_open2',
    title: '关闭网页2',
    canDraggable: true,
    canAfterAdd: true,
    canBeforeAdd: true,
    disabled: false,
    canSelect: true,
    description: '在浏览器中关闭网页',
    initProps: [
      {
        name: 'url',
        title: '网页地址',
        component: 'Input',
        defaultValue: 'www.baidu.com',
      },
    ],
  },
  {
    type: 'brower_open3',
    title: '关闭网页3',
    canDraggable: true,
    canAfterAdd: true,
    canBeforeAdd: true,
    disabled: false,
    canSelect: true,
    description: '在浏览器中关闭网页',
    initProps: [
      {
        name: 'url',
        title: '网页地址',
        component: 'Input',
        defaultValue: 'www.baidu.com',
      },
    ],
  },
  {
    type: 'brower_open4',
    title: '关闭网页4',
    canDraggable: true,
    canAfterAdd: true,
    canBeforeAdd: true,
    disabled: false,
    canSelect: true,
    description: '在浏览器中关闭网页',
    initProps: [
      {
        name: 'url',
        title: '网页地址',
        component: 'Input',
        defaultValue: 'www.baidu.com',
      },
    ],
  },
  {
    type: 'brower_open5',
    title: 'if分支',
    view: 'branch',
    canDraggable: true,
    canAfterAdd: true,
    canBeforeAdd: true,
    disabled: false,
    canSelect: true,
    description: '分支',
    initProps: [
      {
        name: 'url',
        title: '网页地址',
        component: 'Input',
        defaultValue: 'www.baidu.com',
      },
    ],
  },
];
