import brower from './brower';
export default [
  ...brower,
  {
    type: 'root',
    name: '流程',
    canDraggable: false,
    canAfterAdd: false,
    canBeforeAdd: false,
    disabled: false,
    canSelect: false,
  },
  {
    type: 'startNode',
    title: '开始',
    icon: { type: 'iconkaishijiedian' },
    canDraggable: false,
    canAfterAdd: true,
    canBeforeAdd: false,
    disabled: true,
    canSelect: false,
  },
  {
    type: 'endNode',
    title: '结束',
    icon: { type: 'iconjieshujiedian' },
    canDraggable: false,
    canAfterAdd: false,
    canBeforeAdd: true,
    disabled: true,
    canSelect: false,
  },
  {
    type: 'brower_close1',
    title: '捕获窗口',
    icon: { type: 'iconbuzhuokongjian' },
    canDraggable: true,
    canAfterAdd: true,
    canBeforeAdd: true,
    disabled: false,
    canSelect: true,
    description: '在浏览器中关闭网页',
    initProps: [
      {
        name: 'url',
        title: '网页地址',
        component: 'Input',
        defaultValue: 'www.baidu.com',
      },
    ],
  },
  {
    type: 'brower_open1',
    title: '输入热键',
    icon: { type: 'iconxiangsikongjian' },
    canDraggable: true,
    canAfterAdd: true,
    canBeforeAdd: true,
    disabled: false,
    canSelect: true,
    description: '在浏览器中关闭网页',
    initProps: [
      {
        name: 'url',
        title: '网页地址',
        component: 'Input',
        defaultValue: 'www.baidu.com',
      },
    ],
  },
  {
    type: 'brower_open2',
    title: '读取参数面板',
    icon: { type: 'iconbiancheng-keshihua' },
    canDraggable: true,
    canAfterAdd: true,
    canBeforeAdd: true,
    disabled: false,
    canSelect: true,
    description: '在浏览器中关闭网页',
    initProps: [
      {
        name: 'url',
        title: '网页地址',
        component: 'Input',
        defaultValue: 'www.baidu.com',
      },
    ],
  },
  {
    type: 'brower_open3',
    title: '获取文本',
    icon: { type: 'iconliucheng-keshihua' },
    canDraggable: true,
    canAfterAdd: true,
    canBeforeAdd: true,
    disabled: false,
    canSelect: true,
    description: '在浏览器中关闭网页',
    initProps: [
      {
        name: 'url',
        title: '网页地址',
        component: 'Input',
        defaultValue: 'www.baidu.com',
      },
    ],
  },
  {
    type: 'brower_open4',
    title: '打开Excel',
    icon: { type: 'iconcanshumianban-keshihua' },
    canDraggable: true,
    canAfterAdd: true,
    canBeforeAdd: true,
    disabled: false,
    canSelect: true,
    description: '在浏览器中关闭网页',
    initProps: [
      {
        name: 'url',
        title: '网页地址',
        component: 'Input',
        defaultValue: 'www.baidu.com',
      },
    ],
  },
  {
    type: 'brower_open5',
    title: '条件分支',
    view: 'branch',
    icon: { type: 'iconwordcaozuo-keshihua' },
    canDraggable: true,
    canAfterAdd: true,
    canBeforeAdd: true,
    disabled: false,
    canSelect: true,
    description: '分支',
    initProps: [
      {
        name: 'url',
        title: '网页地址',
        component: 'Input',
        defaultValue: 'www.baidu.com',
      },
    ],
  },
];
